# YAML mapping file for GHG data files
# Dynamic fields can reference class attributes using 'self.attributeName'
Project:
  title: 
  id: 
  creation_date: 
  last_change_date: 
  start_date: 
  end_date: 
  file_name: 
  sw_version: 
  ini_version: 

Files:
  data_path: 
  saved_native: 0
  timestamp: 0
  iso_format: 0
  end_of_line: lf
  enable_processing: 1
  tstamp_end: 0

Site:
  site_name: 
  site_id: self.siteID
  altitude: 
  latitude: 
  longitude: 
  canopy_height: 
  displacement_height: 
  roughness_length: 

Station:
  station_name: 
  station_id: self.siteID

Timing:
  acquisition_frequency: self.samplingFrequency
  file_duration: self.databaseInterval
  pc_time_settings: 

Instruments:
  instr_1_manufacturer: 
  instr_1_model: 
  instr_1_sw_version: 
  instr_1_id: 
  instr_1_height: 
  instr_1_wformat: 
  instr_1_wref: 
  instr_1_north_offset: 
  instr_1_northward_separation: 
  instr_1_eastward_separation: 
  instr_1_vertical_separation: 
  instr_1_vpath_length: 
  instr_1_hpath_length: 
  instr_1_tau: 

  instr_n+1_manufacturer: 
  instr_n+1_model: 
  instr_n+1_sw_version: 
  instr_n+1_id: 
  instr_n+1_tube_length: 
  instr_n+1_tube_diameter: 
  instr_n+1_tube_flowrate: 
  instr_n+1_northward_separation: 
  instr_n+1_eastward_separation: 
  instr_n+1_vertical_separation: 
  instr_n+1_vpath_length: 
  instr_n+1_hpath_length: 
  instr_n+1_tau: 
  instr_n+1_kw: 
  instr_n+1_ko: 

FileDescription:
  separator: 
  header_rows: 
  data_label: 
  col_n_variable: 
  col_n_instrument: 
  col_n_measure_type: 
  col_n_unit_in: 
  col_n_min_value: 
  col_n_max_value: 
  col_n_conversion: 
  col_n_unit_out: 
  col_n_a_value: 
  col_n_b_value: 
  col_n_nom_timelag: 
  col_n_min_timelag: 
  col_n_max_timelag: 
